### PR TITLE
Upgrade to Ubuntu 16.04

### PR DESCRIPTION
**Pull request by solidnerd**

### CODE REVIEW

**Comment by sameersbn** [comment]
@solidnerd have you tested the changes after the upgrade?

**Comment by solidnerd** [comment]
Currently not. I will update the title and make some tests with gitlab .

**Comment by nixel2007** [comment]
any work on this?

**Comment by solidnerd** [comment]
@sameersbn I'm using it for a longer time and doesn't see any issue with that. I tested with gitlab database data.

**Comment by sameersbn** [comment]
I've updated the repo to use `ubuntu:bionic-20180526` and make newer releases of with `postgreqsql-9.6` as well as `postgreqsql-10`. As usual the image will automatically migrate the 9.6 data to version 10. But it would be wise to take a backup before upgrading to the newer release series.

**Comment by sameersbn** [comment]
thanks for all you efforts @solidnerd . I really appreciate it :+1:

**Pull request closed without merging**
