### PR TITLE
Release 14-20230622

### PR DESCRIPTION
**Pull request by Aoiujz**

### CODE REVIEW

**Comment by Aoiujz** [comment]
Hi @sameersbn ,

Can you re-run the CircleCI build?
I set up various environments locally and successfully executed docker builds. That error in CircleCI does not appear.

**Comment by sameersbn** [comment]
it's a issue wit docker version on circle ci. I will migrate the CI over to github actions over the weekend

**Comment by Aoiujz** [comment]
Oh, that's right, looking forward to your work.

**Comment by sameersbn** [comment]
sorry about the delay, please rebase your PR and delete any and all changes to `.circleci` folder (it has been deleted)

**Pull request closed without merging**
