### PR TITLE
Protect usernames and database names in "CREATE ROLE", "CREATE DATABA…

### PR DESCRIPTION
**Pull request by sdusart**
…SE" and "GRANT ALL" requests

This enables to use "-" in for usernames or database names (eg myApp-client1).

### CODE REVIEW

**Comment by sameersbn** [comment]
sorry this merge took so long. i completely missed it.

**Comment by sameersbn** [comment]
@sdusart In this PR you have added `DB_LOCALE` option. I have not been able to test it out. Can you please share a sample docker run to test out this setting?

p.s. in the `latest` image this variable has been renamed to `PG_LOCALE`, however for backward compatibility it does recognize the `DB_LOCALE` variable.

**Comment by sameersbn** [comment]
BTW, here is the sample output of  my test

```bash
docker run --name postgre -it --rm --env 'PG_LOCALE=en_US'   sameersbn/postgresqlGenerating locale "en_US"...
Initializing datadir...
Initializing certdir...
Initializing logdir...
Initializing rundir...
Initializing database...
initdb: encoding mismatch
The encoding you selected (UTF8) and the encoding that the
selected locale uses (LATIN1) do not match.  This would lead to
misbehavior in various character string processing functions.
Rerun initdb and either do not specify an encoding explicitly,
or choose a matching combination.
```

**Comment by sdusart** [comment]
Hi @sameersbn, 

the initdb command has an --encoding=unicode argument which seems to conflict with non-unicode locales.

It works well for en_US.utf8 (the image I use here is generated from commit 57f7f65 on sdusart/docker-postgresql) : 
$ docker run --name postgres -it --rm --env 'DB_LOCALE=en_US.utf8' sdusart/postgresql
Generating required locale "en_US.utf8"...
Initializing database...
Starting PostgreSQL server...
2015-11-28 20:16:38 UTC [94-1] LOG:  database system was shut down at 2015-11-28 20:16:38 UTC
2015-11-28 20:16:38 UTC [94-2] LOG:  MultiXact member wraparound protections are now enabled
2015-11-28 20:16:38 UTC [1-1] LOG:  database system is ready to accept connections
2015-11-28 20:16:38 UTC [98-1] LOG:  autovacuum launcher started

but not with en_US as you already noticed.

I think the encoding should be configurable too. 
This way it will be possible to provide a valid combination for encoding and locale (eg SQL_ASCII and en_US). I can send a PR in the next days for this.

**Comment by sdusart** [comment]
BTW I'll send another PR as the locale must not be generated only before initdb as it prevents using a newly created container with an existing data directory whose locale is not the default one (C).

**Comment by sameersbn** [comment]
Hi. I remove the `PG_LOCALE` option since i was not able to get it working. You can revert these commits 

- https://github.com/sameersbn/docker-postgresql/commit/edee0f1ce7f0386ae45e9766ed0001203fc3fb7e
- https://github.com/sameersbn/docker-postgresql/commit/1f87e4aa1bbb9c25593478e52de2caf416c8c6a6 

and add the required support on top of it.

> locale must not be generated only before initd

I had resolved this issue, once you revert the above commits the locale will be generated at every launch.

**Pull request merged**
