### PR TITLE
Updated Postgres version to 14

### PR DESCRIPTION
**Pull request by sramazzina**

### CODE REVIEW

**Comment by bor8** [comment]
Will that be available on hub.docker.com?

**Comment by sramazzina** [comment]
I think it will be made available as soon as they will decide to merge my change. If that will be the option.

**Comment by sameersbn** [comment]
thanks for the contribution. merging

**Comment by Aoiujz** [comment]
Is it possible to push version 14 to the docker registry?

**Comment by kkimurak** [comment]
Please do check what is going on before claiming. CI build fails on shellcheck stage, and it reports following error. We can say that the CI configuration should be updated.

The build log : https://app.circleci.com/jobs/github/sameersbn/docker-postgresql/266

````
Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed.
Cloning git repository

error cloning repository: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
````

See circleci article when github made changes regarding ssh: https://support.circleci.com/hc/en-us/articles/4410498350107-Build-Fails-due-to-SSH-Handshake

**Pull request merged**
