### PR TITLE
add support for USERMAP_* env variables

### LINKED ISSUE #28: Allow user to supply user / group id
In the gitlab image you have both `USERMAP_UID` and `GROUPMAP_UID` configuration variables, which allow the image to use the hosts git user. Would something similar be possible for this image?

I'm relatively new to linux server administration but changing the id's of the postgresql user / group seems to be easily possible from what google tells me and seeing as the ownership of the postgresql home directory is already changed / fixed when starting the image there shouldn't even be any performance overhead.

### PR DESCRIPTION
**Pull request by TimNN**
Fixes #28.

I'm using this right now without any problems, however I'm not sure if there are some hidden caveats I'm unaware of.

### CODE REVIEW

**Comment by sameersbn** [comment]
@TimNN In have merged the PR. Can you please test the changes and let me know. I will make a new point release soon with this change

**Comment by TimNN** [comment]
@sameersbn I have tried `sameersbn/postgresql:latest` and so far it works great!

**Comment by sameersbn** [comment]
@TimNN there is one other PR that I want to merge into before making a new release.

**Comment by TimNN** [comment]
No problem, take your time.

I made similar changes to `sameersbn/redis`, I just need to clean things up a bit and fix the documentation, would you be interested in a pull request?

**Comment by sameersbn** [comment]
@TimNN sure.. as long as it works and does not break anything we're good.

**Pull request merged**
